//! Keybinding glossary, used by the help overlay and command palette.

#[derive(Debug, Clone, Copy)]
pub struct KeyHelp {
    pub keys: &'static str,
    pub action: &'static str,
    pub group: &'static str,
}

pub const GLOSSARY: &[KeyHelp] = &[
    KeyHelp { keys: "Ctrl-P",      action: "Command palette",          group: "Global" },
    KeyHelp { keys: "Ctrl-O",      action: "Quick switcher",           group: "Global" },
    KeyHelp { keys: "Ctrl-Shift-F",action: "Vault search",             group: "Global" },
    KeyHelp { keys: "Ctrl-N",      action: "New note",                 group: "Global" },
    KeyHelp { keys: "Ctrl-S",      action: "Save current note",        group: "Global" },
    KeyHelp { keys: "Ctrl-W",      action: "Close current note",       group: "Global" },
    KeyHelp { keys: "Ctrl-Q",      action: "Quit Onyx",                group: "Global" },
    KeyHelp { keys: "Ctrl-,",      action: "Settings",                 group: "Global" },
    KeyHelp { keys: "Ctrl-/",      action: "Help overlay",             group: "Global" },
    KeyHelp { keys: "F1",          action: "Help overlay",             group: "Global" },

    KeyHelp { keys: "Ctrl-B",      action: "Toggle left column",        group: "Layout" },
    KeyHelp { keys: "Ctrl-R",      action: "Toggle right column",       group: "Layout" },
    KeyHelp { keys: "Ctrl-E",      action: "Toggle preview",           group: "Layout" },
    KeyHelp { keys: "Ctrl-G",      action: "Focus graph pane",         group: "Layout" },
    KeyHelp { keys: "Ctrl-T",      action: "Tags tab",                 group: "Layout" },
    KeyHelp { keys: "Ctrl-K",      action: "Focus calendar pane",      group: "Layout" },
    KeyHelp { keys: "Ctrl-←/→",    action: "Resize editor | preview split", group: "Layout" },
    KeyHelp { keys: "Ctrl-1..4",   action: "Focus pane",               group: "Layout" },
    KeyHelp { keys: "Tab",         action: "Next pane",                group: "Layout" },
    KeyHelp { keys: "Shift-Tab",   action: "Previous pane",            group: "Layout" },

    KeyHelp { keys: "Enter",       action: "Open note (file tree)",    group: "File tree" },
    KeyHelp { keys: "Space",       action: "Expand/collapse folder",   group: "File tree" },
    KeyHelp { keys: "j / k",       action: "Down / up",                group: "File tree" },
    KeyHelp { keys: "n",           action: "New note (in selected folder)", group: "File tree" },
    KeyHelp { keys: "m",           action: "New folder (in selected folder)", group: "File tree" },
    KeyHelp { keys: "d",           action: "Delete selected note",     group: "File tree" },
    KeyHelp { keys: "r",           action: "Rename selected note",     group: "File tree" },

    KeyHelp { keys: "i / a",       action: "Enter insert mode",        group: "Editor (Normal)" },
    KeyHelp { keys: "I / A",       action: "Insert at line start/end", group: "Editor (Normal)" },
    KeyHelp { keys: "o / O",       action: "Open new line below/above",group: "Editor (Normal)" },
    KeyHelp { keys: "Esc",         action: "Return to normal mode",    group: "Editor" },
    KeyHelp { keys: "h j k l",     action: "Cursor motion",            group: "Editor (Normal)" },
    KeyHelp { keys: "w / b",       action: "Word forward / backward",  group: "Editor (Normal)" },
    KeyHelp { keys: "0 / $",       action: "Line start / end",         group: "Editor (Normal)" },
    KeyHelp { keys: "g g / G",     action: "Doc start / end",          group: "Editor (Normal)" },
    KeyHelp { keys: "x",           action: "Delete char",              group: "Editor (Normal)" },
    KeyHelp { keys: "d d",         action: "Delete line",              group: "Editor (Normal)" },
    KeyHelp { keys: "u / Ctrl-R",  action: "Undo / redo",              group: "Editor (Normal)" },
    KeyHelp { keys: "Ctrl-Enter",  action: "Follow wikilink at cursor",group: "Editor" },
    KeyHelp { keys: "[[",          action: "Wikilink autocomplete",    group: "Editor (Insert)" },

    KeyHelp { keys: "h j k l",     action: "Move cursor (calendar)",   group: "Calendar" },
    KeyHelp { keys: "o / Space",   action: "Open daily note for day",  group: "Calendar" },
    KeyHelp { keys: "Enter",       action: "Fullscreen calendar",      group: "Calendar" },
    KeyHelp { keys: "t",           action: "Jump to today",            group: "Calendar" },

    KeyHelp { keys: "Enter",       action: "Fullscreen graph",         group: "Graph" },
    KeyHelp { keys: "a",           action: "Toggle local / all-notes scope", group: "Graph" },
    KeyHelp { keys: "o",           action: "Open centered note",       group: "Graph" },
    KeyHelp { keys: "Esc",         action: "Exit fullscreen / pane",   group: "Graph" },

    KeyHelp { keys: "type",        action: "Edit scratch (autosaves)", group: "Quicknote" },
    KeyHelp { keys: "Tab / Esc",   action: "Leave (saves)",            group: "Quicknote" },

    KeyHelp { keys: "j / k",       action: "Move selection",           group: "Todo" },
    KeyHelp { keys: "Space",       action: "Toggle done",              group: "Todo" },
    KeyHelp { keys: "a",           action: "Add todo",                 group: "Todo" },
    KeyHelp { keys: "e",           action: "Edit todo",                group: "Todo" },
    KeyHelp { keys: "d",           action: "Delete todo",              group: "Todo" },

    KeyHelp { keys: "Type to filter",action: "Fuzzy search items",     group: "Palette / Switcher" },
    KeyHelp { keys: "Enter",       action: "Select",                   group: "Palette / Switcher" },
    KeyHelp { keys: "Esc",         action: "Cancel",                   group: "Palette / Switcher" },

    KeyHelp { keys: ":",           action: "Open ex command line",     group: "Ex commands (vim)" },
    KeyHelp { keys: ":q  :q!",     action: "Quit (force-quit)",        group: "Ex commands (vim)" },
    KeyHelp { keys: ":w",          action: "Write (save) current note",group: "Ex commands (vim)" },
    KeyHelp { keys: ":wq  :x",     action: "Save and quit",            group: "Ex commands (vim)" },
    KeyHelp { keys: ":e <name>",   action: "Edit / open a note",       group: "Ex commands (vim)" },
    KeyHelp { keys: ":new <path>", action: "Create a note (Folder/Name ok)", group: "Ex commands (vim)" },
    KeyHelp { keys: ":mkdir <path>",action: "Create a folder",          group: "Ex commands (vim)" },
    KeyHelp { keys: ":help",       action: "Open this help",           group: "Ex commands (vim)" },
    KeyHelp { keys: ":today",      action: "Open today's daily note",  group: "Ex commands (vim)" },
    KeyHelp { keys: ":graph",      action: "Open graph view",          group: "Ex commands (vim)" },
    KeyHelp { keys: ":preview",    action: "Toggle preview pane",      group: "Ex commands (vim)" },
    KeyHelp { keys: ":search <q>", action: "Vault content search",     group: "Ex commands (vim)" },
    KeyHelp { keys: ":rename <n>", action: "Rename current note",      group: "Ex commands (vim)" },
    KeyHelp { keys: ":delete",     action: "Delete current note",      group: "Ex commands (vim)" },
    KeyHelp { keys: ":vault <p>",  action: "Open / create vault",      group: "Ex commands (vim)" },
    KeyHelp { keys: ":set theme=…",action: "Switch theme",             group: "Ex commands (vim)" },
    KeyHelp { keys: ":set (no)preview / (no)numbers / (no)wrap", action: "Toggle a layout/editor switch", group: "Ex commands (vim)" },
    KeyHelp { keys: ":set editor-width=N", action: "Editor pane width (20-80%)", group: "Ex commands (vim)" },
    KeyHelp { keys: ":<N>",        action: "Jump to line N",           group: "Ex commands (vim)" },
    KeyHelp { keys: ":calendar",   action: "Focus calendar pane",      group: "Ex commands (vim)" },
    KeyHelp { keys: ":todo",       action: "Focus todo checklist",     group: "Ex commands (vim)" },
    KeyHelp { keys: ":quicknote",  action: "Focus quicknote scratch",  group: "Ex commands (vim)" },
    KeyHelp { keys: "Up / Down",   action: "Scroll command history",   group: "Ex commands (vim)" },

    KeyHelp { keys: ":fzf",        action: "Fuzzy find files (fzf)",   group: "External tools" },
    KeyHelp { keys: ":rg",         action: "Live grep contents (fzf+rg)", group: "External tools" },
    KeyHelp { keys: ":yazi",       action: "File browser w/ PDF & image preview", group: "External tools" },
    KeyHelp { keys: ":Telescope find_files", action: "Quick switcher",  group: "Telescope-style" },
    KeyHelp { keys: ":Telescope live_grep",  action: "Live grep w/ preview (fzf+rg)", group: "Telescope-style" },
    KeyHelp { keys: ":Telescope native_grep",action: "Vault search (in-process)", group: "Telescope-style" },
    KeyHelp { keys: ":Telescope buffers",    action: "Recent notes",    group: "Telescope-style" },
    KeyHelp { keys: ":Telescope help_tags",  action: "This help",       group: "Telescope-style" },
    KeyHelp { keys: ":Telescope file_browser", action: "Open yazi",     group: "Telescope-style" },
];
